# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/sdm439-common/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/xiaomi/sdm439-common

# Inherit fragments
$(call inherit-product, vendor/xiaomi/sdm439-common/sdm439-common-vendor-keymaster.mk)
$(call inherit-product, vendor/xiaomi/sdm439-common/sdm439-common-vendor-gatekeeper.mk)
$(call inherit-product, vendor/xiaomi/sdm439-common/sdm439-common-vendor-partial_ril.mk)
$(call inherit-product, vendor/xiaomi/sdm439-common/sdm439-common-vendor-qcrild.mk)
$(call inherit-product, vendor/xiaomi/sdm439-common/sdm439-common-vendor-qtee.mk)
